Implement cameras launch file with synchronisation
ipab-rad/av_camera pull request #13
Opened 2024-11-05 18:50 UTC by GreatAlexander

- Use ROS2 spinnaker synchronized camera driver instead of default
 - Modify camera config parameter yaml files to fit new structure
 - Add exposure controller parameters as required
 - Update all_cams.launch.xml to run all cameras in single node
 - NOTE: Change exposure target to 1ms
 - NOTE: Also compute brightness in /meta as it may be useful

2024-11-06 12:12 UTC, hect95 requested changes

2024-11-06 12:12 UTC, hect95 commented on av_camera_launch/config/fsp_l_config.yaml
> +      exposure_time: 5000
I think we want this at `1ms` ? 
```suggestion
      exposure_time: 1000
```

2024-11-06 12:12 UTC, hect95 commented on av_camera_launch/launch/all_cams.launch.xml
> +      <composable_node pkg="spinnaker_synchronized_camera_driver" plugin="spinnaker_synchronized_camera_driver::SynchronizedCameraDriver" name="camera" namespace="/sensor">
Wouldn't the composable node grasp the `namespace` defined above? 

Can we call this node `spinnaker_camera_sync_node` ? :)

2024-11-06 12:18 UTC, hect95 commented on av_camera_launch/config/fsp_l_config.yaml
> +      exposure_time: 5000
Fixed hehe

2024-11-19 18:32 UTC, GreatAlexander commented
NOTE:
 - We need to enable compute brightness to use the exposure controller as part of the synchronised driver
 - Unfortunately, BayerBG8 (inverse images) is not supported for computing brightness. So temporarily until it is fixed upstream we will revert to `gain_auto` "Continuous" and `compute_brightness` "False"

2024-11-26 11:23 UTC, merged